// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

// Set account email address
func GetEmail(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "onepassword:email")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "OP_EMAIL").(string); ok {
		return dv
	}
	return v
}

// Set account password
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "onepassword:password")
}

// Set account secret key
func GetSecretKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "onepassword:secretKey")
}

// Set alternative subdomain for 1password. From [subdomain].1password.com
func GetSubdomain(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "onepassword:subdomain")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "OP_SUBDOMAIN").(string); ok {
		return dv
	}
	return v
}
