// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";

export interface CommonSection {
    fields?: pulumi.Input<pulumi.Input<inputs.CommonSectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface CommonSectionField {
    address?: pulumi.Input<inputs.CommonSectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface CommonSectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface CreditCardMain {
    cardholder?: pulumi.Input<string>;
    cvv?: pulumi.Input<string>;
    expiryDate?: pulumi.Input<number>;
    fields?: pulumi.Input<pulumi.Input<inputs.CreditCardMainField>[]>;
    number?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    validFrom?: pulumi.Input<number>;
}

export interface CreditCardMainField {
    address?: pulumi.Input<inputs.CreditCardMainFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface CreditCardMainFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface CreditCardSection {
    fields?: pulumi.Input<pulumi.Input<inputs.CreditCardSectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface CreditCardSectionField {
    address?: pulumi.Input<inputs.CreditCardSectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface CreditCardSectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface GetCommonSection {
    fields?: inputs.GetCommonSectionField[];
    name?: string;
}

export interface GetCommonSectionField {
    address?: inputs.GetCommonSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetCommonSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetCreditCardMain {
    cardholder?: string;
    cvv?: string;
    expiryDate?: number;
    fields?: inputs.GetCreditCardMainField[];
    number?: string;
    title?: string;
    type?: string;
    validFrom?: number;
}

export interface GetCreditCardMainField {
    address?: inputs.GetCreditCardMainFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetCreditCardMainFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetCreditCardSection {
    fields?: inputs.GetCreditCardSectionField[];
    name?: string;
}

export interface GetCreditCardSectionField {
    address?: inputs.GetCreditCardSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetCreditCardSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityAddress {
    address?: inputs.GetIdentityAddressAddress;
    businessPhone?: string;
    cellPhone?: string;
    defaultPhone?: string;
    fields?: inputs.GetIdentityAddressField[];
    homePhone?: string;
    title?: string;
}

export interface GetIdentityAddressAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityAddressField {
    address?: inputs.GetIdentityAddressFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentityAddressFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityIdentification {
    birthDate?: number;
    company?: string;
    department?: string;
    fields?: inputs.GetIdentityIdentificationField[];
    firstname?: string;
    initial?: string;
    jobTitle?: string;
    lastname?: string;
    occupation?: string;
    sex?: string;
    title?: string;
}

export interface GetIdentityIdentificationField {
    address?: inputs.GetIdentityIdentificationFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentityIdentificationFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityInternet {
    email?: string;
    fields?: inputs.GetIdentityInternetField[];
    title?: string;
    username?: string;
}

export interface GetIdentityInternetField {
    address?: inputs.GetIdentityInternetFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentityInternetFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentitySection {
    fields?: inputs.GetIdentitySectionField[];
    name?: string;
}

export interface GetIdentitySectionField {
    address?: inputs.GetIdentitySectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentitySectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetLoginSection {
    fields?: inputs.GetLoginSectionField[];
    name?: string;
}

export interface GetLoginSectionField {
    address?: inputs.GetLoginSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetLoginSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetPasswordSection {
    fields?: inputs.GetPasswordSectionField[];
    name?: string;
}

export interface GetPasswordSectionField {
    address?: inputs.GetPasswordSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetPasswordSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetSecureNoteSection {
    fields?: inputs.GetSecureNoteSectionField[];
    name?: string;
}

export interface GetSecureNoteSectionField {
    address?: inputs.GetSecureNoteSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetSecureNoteSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetSoftwareLicenseMain {
    fields?: inputs.GetSoftwareLicenseMainField[];
    licenseKey?: string;
    title?: string;
}

export interface GetSoftwareLicenseMainField {
    address?: inputs.GetSoftwareLicenseMainFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetSoftwareLicenseMainFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetSoftwareLicenseSection {
    fields?: inputs.GetSoftwareLicenseSectionField[];
    name?: string;
}

export interface GetSoftwareLicenseSectionField {
    address?: inputs.GetSoftwareLicenseSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetSoftwareLicenseSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface IdentityAddress {
    address?: pulumi.Input<inputs.IdentityAddressAddress>;
    businessPhone?: pulumi.Input<string>;
    cellPhone?: pulumi.Input<string>;
    defaultPhone?: pulumi.Input<string>;
    fields?: pulumi.Input<pulumi.Input<inputs.IdentityAddressField>[]>;
    homePhone?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
}

export interface IdentityAddressAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface IdentityAddressField {
    address?: pulumi.Input<inputs.IdentityAddressFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface IdentityAddressFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface IdentityIdentification {
    birthDate?: pulumi.Input<number>;
    company?: pulumi.Input<string>;
    department?: pulumi.Input<string>;
    fields?: pulumi.Input<pulumi.Input<inputs.IdentityIdentificationField>[]>;
    firstname?: pulumi.Input<string>;
    initial?: pulumi.Input<string>;
    jobTitle?: pulumi.Input<string>;
    lastname?: pulumi.Input<string>;
    occupation?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
}

export interface IdentityIdentificationField {
    address?: pulumi.Input<inputs.IdentityIdentificationFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface IdentityIdentificationFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface IdentityInternet {
    email?: pulumi.Input<string>;
    fields?: pulumi.Input<pulumi.Input<inputs.IdentityInternetField>[]>;
    title?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface IdentityInternetField {
    address?: pulumi.Input<inputs.IdentityInternetFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface IdentityInternetFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface IdentitySection {
    fields?: pulumi.Input<pulumi.Input<inputs.IdentitySectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface IdentitySectionField {
    address?: pulumi.Input<inputs.IdentitySectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface IdentitySectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface LoginSection {
    fields?: pulumi.Input<pulumi.Input<inputs.LoginSectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface LoginSectionField {
    address?: pulumi.Input<inputs.LoginSectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface LoginSectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface PasswordSection {
    fields?: pulumi.Input<pulumi.Input<inputs.PasswordSectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface PasswordSectionField {
    address?: pulumi.Input<inputs.PasswordSectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface PasswordSectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface SecureNoteSection {
    fields?: pulumi.Input<pulumi.Input<inputs.SecureNoteSectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface SecureNoteSectionField {
    address?: pulumi.Input<inputs.SecureNoteSectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface SecureNoteSectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface SoftwareLicenseMain {
    fields?: pulumi.Input<pulumi.Input<inputs.SoftwareLicenseMainField>[]>;
    licenseKey?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
}

export interface SoftwareLicenseMainField {
    address?: pulumi.Input<inputs.SoftwareLicenseMainFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface SoftwareLicenseMainFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}

export interface SoftwareLicenseSection {
    fields?: pulumi.Input<pulumi.Input<inputs.SoftwareLicenseSectionField>[]>;
    name?: pulumi.Input<string>;
}

export interface SoftwareLicenseSectionField {
    address?: pulumi.Input<inputs.SoftwareLicenseSectionFieldAddress>;
    cardType?: pulumi.Input<string>;
    concealed?: pulumi.Input<string>;
    date?: pulumi.Input<number>;
    email?: pulumi.Input<string>;
    monthYear?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    phone?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    sex?: pulumi.Input<string>;
    string?: pulumi.Input<string>;
    totp?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface SoftwareLicenseSectionFieldAddress {
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    street?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}
