// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as outputs from "../types/output";

export interface CommonSection {
    fields?: outputs.CommonSectionField[];
    name?: string;
}

export interface CommonSectionField {
    address?: outputs.CommonSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface CommonSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface CreditCardMain {
    cardholder?: string;
    cvv?: string;
    expiryDate?: number;
    fields?: outputs.CreditCardMainField[];
    number?: string;
    title?: string;
    type?: string;
    validFrom?: number;
}

export interface CreditCardMainField {
    address?: outputs.CreditCardMainFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface CreditCardMainFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface CreditCardSection {
    fields?: outputs.CreditCardSectionField[];
    name?: string;
}

export interface CreditCardSectionField {
    address?: outputs.CreditCardSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface CreditCardSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetCommonSection {
    fields?: outputs.GetCommonSectionField[];
    name?: string;
}

export interface GetCommonSectionField {
    address?: outputs.GetCommonSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetCommonSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetCreditCardMain {
    cardholder?: string;
    cvv?: string;
    expiryDate?: number;
    fields?: outputs.GetCreditCardMainField[];
    number?: string;
    title?: string;
    type?: string;
    validFrom?: number;
}

export interface GetCreditCardMainField {
    address?: outputs.GetCreditCardMainFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetCreditCardMainFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetCreditCardSection {
    fields?: outputs.GetCreditCardSectionField[];
    name?: string;
}

export interface GetCreditCardSectionField {
    address?: outputs.GetCreditCardSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetCreditCardSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityAddress {
    address?: outputs.GetIdentityAddressAddress;
    businessPhone?: string;
    cellPhone?: string;
    defaultPhone?: string;
    fields?: outputs.GetIdentityAddressField[];
    homePhone?: string;
    title?: string;
}

export interface GetIdentityAddressAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityAddressField {
    address?: outputs.GetIdentityAddressFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentityAddressFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityIdentification {
    birthDate?: number;
    company?: string;
    department?: string;
    fields?: outputs.GetIdentityIdentificationField[];
    firstname?: string;
    initial?: string;
    jobTitle?: string;
    lastname?: string;
    occupation?: string;
    sex?: string;
    title?: string;
}

export interface GetIdentityIdentificationField {
    address?: outputs.GetIdentityIdentificationFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentityIdentificationFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentityInternet {
    email?: string;
    fields?: outputs.GetIdentityInternetField[];
    title?: string;
    username?: string;
}

export interface GetIdentityInternetField {
    address?: outputs.GetIdentityInternetFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentityInternetFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetIdentitySection {
    fields?: outputs.GetIdentitySectionField[];
    name?: string;
}

export interface GetIdentitySectionField {
    address?: outputs.GetIdentitySectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetIdentitySectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetLoginSection {
    fields?: outputs.GetLoginSectionField[];
    name?: string;
}

export interface GetLoginSectionField {
    address?: outputs.GetLoginSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetLoginSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetPasswordSection {
    fields?: outputs.GetPasswordSectionField[];
    name?: string;
}

export interface GetPasswordSectionField {
    address?: outputs.GetPasswordSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetPasswordSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetSecureNoteSection {
    fields?: outputs.GetSecureNoteSectionField[];
    name?: string;
}

export interface GetSecureNoteSectionField {
    address?: outputs.GetSecureNoteSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetSecureNoteSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetSoftwareLicenseMain {
    fields?: outputs.GetSoftwareLicenseMainField[];
    licenseKey?: string;
    title?: string;
}

export interface GetSoftwareLicenseMainField {
    address?: outputs.GetSoftwareLicenseMainFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetSoftwareLicenseMainFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface GetSoftwareLicenseSection {
    fields?: outputs.GetSoftwareLicenseSectionField[];
    name?: string;
}

export interface GetSoftwareLicenseSectionField {
    address?: outputs.GetSoftwareLicenseSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface GetSoftwareLicenseSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface IdentityAddress {
    address?: outputs.IdentityAddressAddress;
    businessPhone?: string;
    cellPhone?: string;
    defaultPhone?: string;
    fields?: outputs.IdentityAddressField[];
    homePhone?: string;
    title?: string;
}

export interface IdentityAddressAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface IdentityAddressField {
    address?: outputs.IdentityAddressFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface IdentityAddressFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface IdentityIdentification {
    birthDate?: number;
    company?: string;
    department?: string;
    fields?: outputs.IdentityIdentificationField[];
    firstname?: string;
    initial?: string;
    jobTitle?: string;
    lastname?: string;
    occupation?: string;
    sex?: string;
    title?: string;
}

export interface IdentityIdentificationField {
    address?: outputs.IdentityIdentificationFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface IdentityIdentificationFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface IdentityInternet {
    email?: string;
    fields?: outputs.IdentityInternetField[];
    title?: string;
    username?: string;
}

export interface IdentityInternetField {
    address?: outputs.IdentityInternetFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface IdentityInternetFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface IdentitySection {
    fields?: outputs.IdentitySectionField[];
    name?: string;
}

export interface IdentitySectionField {
    address?: outputs.IdentitySectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface IdentitySectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface LoginSection {
    fields?: outputs.LoginSectionField[];
    name?: string;
}

export interface LoginSectionField {
    address?: outputs.LoginSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface LoginSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface PasswordSection {
    fields?: outputs.PasswordSectionField[];
    name?: string;
}

export interface PasswordSectionField {
    address?: outputs.PasswordSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface PasswordSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface SecureNoteSection {
    fields?: outputs.SecureNoteSectionField[];
    name?: string;
}

export interface SecureNoteSectionField {
    address?: outputs.SecureNoteSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface SecureNoteSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface SoftwareLicenseMain {
    fields?: outputs.SoftwareLicenseMainField[];
    licenseKey?: string;
    title?: string;
}

export interface SoftwareLicenseMainField {
    address?: outputs.SoftwareLicenseMainFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface SoftwareLicenseMainFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}

export interface SoftwareLicenseSection {
    fields?: outputs.SoftwareLicenseSectionField[];
    name?: string;
}

export interface SoftwareLicenseSectionField {
    address?: outputs.SoftwareLicenseSectionFieldAddress;
    cardType?: string;
    concealed?: string;
    date?: number;
    email?: string;
    monthYear?: number;
    name?: string;
    phone?: string;
    reference?: string;
    sex?: string;
    string?: string;
    totp?: string;
    url?: string;
}

export interface SoftwareLicenseSectionFieldAddress {
    city?: string;
    country?: string;
    region?: string;
    state?: string;
    street?: string;
    zip?: string;
}
