// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Common struct {
	s *pulumi.ResourceState
}

// NewCommon registers a new resource with the given unique name, arguments, and options.
func NewCommon(ctx *pulumi.Context,
	name string, args *CommonArgs, opts ...pulumi.ResourceOpt) (*Common, error) {
	if args == nil || args.Template == nil {
		return nil, errors.New("missing required argument 'Template'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["name"] = nil
		inputs["notes"] = nil
		inputs["sections"] = nil
		inputs["tags"] = nil
		inputs["template"] = nil
		inputs["vault"] = nil
	} else {
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["template"] = args.Template
		inputs["vault"] = args.Vault
	}
	s, err := ctx.RegisterResource("onepassword:index/common:Common", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Common{s: s}, nil
}

// GetCommon gets an existing Common resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCommon(ctx *pulumi.Context,
	name string, id pulumi.ID, state *CommonState, opts ...pulumi.ResourceOpt) (*Common, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["name"] = state.Name
		inputs["notes"] = state.Notes
		inputs["sections"] = state.Sections
		inputs["tags"] = state.Tags
		inputs["template"] = state.Template
		inputs["vault"] = state.Vault
	}
	s, err := ctx.ReadResource("onepassword:index/common:Common", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Common{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Common) URN() pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Common) ID() pulumi.IDOutput {
	return r.s.ID()
}

func (r *Common) Name() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["name"])
}

func (r *Common) Notes() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["notes"])
}

func (r *Common) Sections() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["sections"])
}

func (r *Common) Tags() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["tags"])
}

func (r *Common) Template() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["template"])
}

func (r *Common) Vault() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["vault"])
}

// Input properties used for looking up and filtering Common resources.
type CommonState struct {
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Template interface{}
	Vault interface{}
}

// The set of arguments for constructing a Common resource.
type CommonArgs struct {
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Template interface{}
	Vault interface{}
}
