// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupCreditCard(ctx *pulumi.Context, args *GetCreditCardArgs) (*GetCreditCardResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["main"] = args.Main
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["vault"] = args.Vault
	}
	outputs, err := ctx.Invoke("onepassword:index/getCreditCard:getCreditCard", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCreditCardResult{
		Main: outputs["main"],
		Name: outputs["name"],
		Notes: outputs["notes"],
		Sections: outputs["sections"],
		Tags: outputs["tags"],
		Vault: outputs["vault"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCreditCard.
type GetCreditCardArgs struct {
	Main interface{}
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
}

// A collection of values returned by getCreditCard.
type GetCreditCardResult struct {
	Main interface{}
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
