// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupCommon(ctx *pulumi.Context, args *GetCommonArgs) (*GetCommonResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["template"] = args.Template
		inputs["vault"] = args.Vault
	}
	outputs, err := ctx.Invoke("onepassword:index/getCommon:getCommon", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCommonResult{
		Name: outputs["name"],
		Notes: outputs["notes"],
		Sections: outputs["sections"],
		Tags: outputs["tags"],
		Template: outputs["template"],
		Vault: outputs["vault"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCommon.
type GetCommonArgs struct {
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Template interface{}
	Vault interface{}
}

// A collection of values returned by getCommon.
type GetCommonResult struct {
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Template interface{}
	Vault interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
