// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupDocument(ctx *pulumi.Context, args *GetDocumentArgs) (*GetDocumentResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["content"] = args.Content
		inputs["name"] = args.Name
		inputs["tags"] = args.Tags
		inputs["vault"] = args.Vault
	}
	outputs, err := ctx.Invoke("onepassword:index/getDocument:getDocument", inputs)
	if err != nil {
		return nil, err
	}
	return &GetDocumentResult{
		Content: outputs["content"],
		Name: outputs["name"],
		Tags: outputs["tags"],
		Vault: outputs["vault"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getDocument.
type GetDocumentArgs struct {
	Content interface{}
	Name interface{}
	Tags interface{}
	Vault interface{}
}

// A collection of values returned by getDocument.
type GetDocumentResult struct {
	Content interface{}
	Name interface{}
	Tags interface{}
	Vault interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
