// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupIdentity(ctx *pulumi.Context, args *GetIdentityArgs) (*GetIdentityResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["address"] = args.Address
		inputs["identification"] = args.Identification
		inputs["internet"] = args.Internet
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["vault"] = args.Vault
	}
	outputs, err := ctx.Invoke("onepassword:index/getIdentity:getIdentity", inputs)
	if err != nil {
		return nil, err
	}
	return &GetIdentityResult{
		Address: outputs["address"],
		Identification: outputs["identification"],
		Internet: outputs["internet"],
		Name: outputs["name"],
		Notes: outputs["notes"],
		Sections: outputs["sections"],
		Tags: outputs["tags"],
		Vault: outputs["vault"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getIdentity.
type GetIdentityArgs struct {
	Address interface{}
	Identification interface{}
	Internet interface{}
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
}

// A collection of values returned by getIdentity.
type GetIdentityResult struct {
	Address interface{}
	Identification interface{}
	Internet interface{}
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
