// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupPassword(ctx *pulumi.Context, args *GetPasswordArgs) (*GetPasswordResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["password"] = args.Password
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["url"] = args.Url
		inputs["vault"] = args.Vault
	}
	outputs, err := ctx.Invoke("onepassword:index/getPassword:getPassword", inputs)
	if err != nil {
		return nil, err
	}
	return &GetPasswordResult{
		Name: outputs["name"],
		Notes: outputs["notes"],
		Password: outputs["password"],
		Sections: outputs["sections"],
		Tags: outputs["tags"],
		Url: outputs["url"],
		Vault: outputs["vault"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getPassword.
type GetPasswordArgs struct {
	Name interface{}
	Notes interface{}
	Password interface{}
	Sections interface{}
	Tags interface{}
	Url interface{}
	Vault interface{}
}

// A collection of values returned by getPassword.
type GetPasswordResult struct {
	Name interface{}
	Notes interface{}
	Password interface{}
	Sections interface{}
	Tags interface{}
	Url interface{}
	Vault interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
