// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Identity struct {
	s *pulumi.ResourceState
}

// NewIdentity registers a new resource with the given unique name, arguments, and options.
func NewIdentity(ctx *pulumi.Context,
	name string, args *IdentityArgs, opts ...pulumi.ResourceOpt) (*Identity, error) {
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["address"] = nil
		inputs["identification"] = nil
		inputs["internet"] = nil
		inputs["name"] = nil
		inputs["notes"] = nil
		inputs["sections"] = nil
		inputs["tags"] = nil
		inputs["vault"] = nil
	} else {
		inputs["address"] = args.Address
		inputs["identification"] = args.Identification
		inputs["internet"] = args.Internet
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["vault"] = args.Vault
	}
	s, err := ctx.RegisterResource("onepassword:index/identity:Identity", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Identity{s: s}, nil
}

// GetIdentity gets an existing Identity resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIdentity(ctx *pulumi.Context,
	name string, id pulumi.ID, state *IdentityState, opts ...pulumi.ResourceOpt) (*Identity, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["address"] = state.Address
		inputs["identification"] = state.Identification
		inputs["internet"] = state.Internet
		inputs["name"] = state.Name
		inputs["notes"] = state.Notes
		inputs["sections"] = state.Sections
		inputs["tags"] = state.Tags
		inputs["vault"] = state.Vault
	}
	s, err := ctx.ReadResource("onepassword:index/identity:Identity", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Identity{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Identity) URN() pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Identity) ID() pulumi.IDOutput {
	return r.s.ID()
}

func (r *Identity) Address() pulumi.Output {
	return r.s.State["address"]
}

func (r *Identity) Identification() pulumi.Output {
	return r.s.State["identification"]
}

func (r *Identity) Internet() pulumi.Output {
	return r.s.State["internet"]
}

func (r *Identity) Name() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["name"])
}

func (r *Identity) Notes() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["notes"])
}

func (r *Identity) Sections() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["sections"])
}

func (r *Identity) Tags() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["tags"])
}

func (r *Identity) Vault() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["vault"])
}

// Input properties used for looking up and filtering Identity resources.
type IdentityState struct {
	Address interface{}
	Identification interface{}
	Internet interface{}
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
}

// The set of arguments for constructing a Identity resource.
type IdentityArgs struct {
	Address interface{}
	Identification interface{}
	Internet interface{}
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
}
