// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Password struct {
	s *pulumi.ResourceState
}

// NewPassword registers a new resource with the given unique name, arguments, and options.
func NewPassword(ctx *pulumi.Context,
	name string, args *PasswordArgs, opts ...pulumi.ResourceOpt) (*Password, error) {
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["name"] = nil
		inputs["notes"] = nil
		inputs["password"] = nil
		inputs["sections"] = nil
		inputs["tags"] = nil
		inputs["url"] = nil
		inputs["vault"] = nil
	} else {
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["password"] = args.Password
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["url"] = args.Url
		inputs["vault"] = args.Vault
	}
	s, err := ctx.RegisterResource("onepassword:index/password:Password", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Password{s: s}, nil
}

// GetPassword gets an existing Password resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPassword(ctx *pulumi.Context,
	name string, id pulumi.ID, state *PasswordState, opts ...pulumi.ResourceOpt) (*Password, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["name"] = state.Name
		inputs["notes"] = state.Notes
		inputs["password"] = state.Password
		inputs["sections"] = state.Sections
		inputs["tags"] = state.Tags
		inputs["url"] = state.Url
		inputs["vault"] = state.Vault
	}
	s, err := ctx.ReadResource("onepassword:index/password:Password", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Password{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Password) URN() pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Password) ID() pulumi.IDOutput {
	return r.s.ID()
}

func (r *Password) Name() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["name"])
}

func (r *Password) Notes() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["notes"])
}

func (r *Password) Password() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["password"])
}

func (r *Password) Sections() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["sections"])
}

func (r *Password) Tags() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["tags"])
}

func (r *Password) Url() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["url"])
}

func (r *Password) Vault() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["vault"])
}

// Input properties used for looking up and filtering Password resources.
type PasswordState struct {
	Name interface{}
	Notes interface{}
	Password interface{}
	Sections interface{}
	Tags interface{}
	Url interface{}
	Vault interface{}
}

// The set of arguments for constructing a Password resource.
type PasswordArgs struct {
	Name interface{}
	Notes interface{}
	Password interface{}
	Sections interface{}
	Tags interface{}
	Url interface{}
	Vault interface{}
}
