// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type SecureNote struct {
	s *pulumi.ResourceState
}

// NewSecureNote registers a new resource with the given unique name, arguments, and options.
func NewSecureNote(ctx *pulumi.Context,
	name string, args *SecureNoteArgs, opts ...pulumi.ResourceOpt) (*SecureNote, error) {
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["name"] = nil
		inputs["notes"] = nil
		inputs["sections"] = nil
		inputs["tags"] = nil
		inputs["vault"] = nil
	} else {
		inputs["name"] = args.Name
		inputs["notes"] = args.Notes
		inputs["sections"] = args.Sections
		inputs["tags"] = args.Tags
		inputs["vault"] = args.Vault
	}
	s, err := ctx.RegisterResource("onepassword:index/secureNote:SecureNote", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &SecureNote{s: s}, nil
}

// GetSecureNote gets an existing SecureNote resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecureNote(ctx *pulumi.Context,
	name string, id pulumi.ID, state *SecureNoteState, opts ...pulumi.ResourceOpt) (*SecureNote, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["name"] = state.Name
		inputs["notes"] = state.Notes
		inputs["sections"] = state.Sections
		inputs["tags"] = state.Tags
		inputs["vault"] = state.Vault
	}
	s, err := ctx.ReadResource("onepassword:index/secureNote:SecureNote", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &SecureNote{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *SecureNote) URN() pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *SecureNote) ID() pulumi.IDOutput {
	return r.s.ID()
}

func (r *SecureNote) Name() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["name"])
}

func (r *SecureNote) Notes() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["notes"])
}

func (r *SecureNote) Sections() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["sections"])
}

func (r *SecureNote) Tags() pulumi.ArrayOutput {
	return (pulumi.ArrayOutput)(r.s.State["tags"])
}

func (r *SecureNote) Vault() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["vault"])
}

// Input properties used for looking up and filtering SecureNote resources.
type SecureNoteState struct {
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
}

// The set of arguments for constructing a SecureNote resource.
type SecureNoteArgs struct {
	Name interface{}
	Notes interface{}
	Sections interface{}
	Tags interface{}
	Vault interface{}
}
