// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Vault struct {
	s *pulumi.ResourceState
}

// NewVault registers a new resource with the given unique name, arguments, and options.
func NewVault(ctx *pulumi.Context,
	name string, args *VaultArgs, opts ...pulumi.ResourceOpt) (*Vault, error) {
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["name"] = nil
	} else {
		inputs["name"] = args.Name
	}
	s, err := ctx.RegisterResource("onepassword:index/vault:Vault", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Vault{s: s}, nil
}

// GetVault gets an existing Vault resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVault(ctx *pulumi.Context,
	name string, id pulumi.ID, state *VaultState, opts ...pulumi.ResourceOpt) (*Vault, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["name"] = state.Name
	}
	s, err := ctx.ReadResource("onepassword:index/vault:Vault", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Vault{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Vault) URN() pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Vault) ID() pulumi.IDOutput {
	return r.s.ID()
}

func (r *Vault) Name() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["name"])
}

// Input properties used for looking up and filtering Vault resources.
type VaultState struct {
	Name interface{}
}

// The set of arguments for constructing a Vault resource.
type VaultArgs struct {
	Name interface{}
}
