// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Identity extends pulumi.CustomResource {
    /**
     * Get an existing Identity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityState, opts?: pulumi.CustomResourceOptions): Identity {
        return new Identity(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'onepassword:index/identity:Identity';

    /**
     * Returns true if the given object is an instance of Identity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Identity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Identity.__pulumiType;
    }

    public readonly address!: pulumi.Output<outputs.IdentityAddress | undefined>;
    public readonly identification!: pulumi.Output<outputs.IdentityIdentification | undefined>;
    public readonly internet!: pulumi.Output<outputs.IdentityInternet | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly notes!: pulumi.Output<string | undefined>;
    public readonly sections!: pulumi.Output<outputs.IdentitySection[] | undefined>;
    public readonly tags!: pulumi.Output<string[] | undefined>;
    public readonly vault!: pulumi.Output<string | undefined>;

    /**
     * Create a Identity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IdentityArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityArgs | IdentityState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as IdentityState | undefined;
            inputs["address"] = state ? state.address : undefined;
            inputs["identification"] = state ? state.identification : undefined;
            inputs["internet"] = state ? state.internet : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["notes"] = state ? state.notes : undefined;
            inputs["sections"] = state ? state.sections : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["vault"] = state ? state.vault : undefined;
        } else {
            const args = argsOrState as IdentityArgs | undefined;
            inputs["address"] = args ? args.address : undefined;
            inputs["identification"] = args ? args.identification : undefined;
            inputs["internet"] = args ? args.internet : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["notes"] = args ? args.notes : undefined;
            inputs["sections"] = args ? args.sections : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["vault"] = args ? args.vault : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Identity.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Identity resources.
 */
export interface IdentityState {
    readonly address?: pulumi.Input<inputs.IdentityAddress>;
    readonly identification?: pulumi.Input<inputs.IdentityIdentification>;
    readonly internet?: pulumi.Input<inputs.IdentityInternet>;
    readonly name?: pulumi.Input<string>;
    readonly notes?: pulumi.Input<string>;
    readonly sections?: pulumi.Input<pulumi.Input<inputs.IdentitySection>[]>;
    readonly tags?: pulumi.Input<pulumi.Input<string>[]>;
    readonly vault?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Identity resource.
 */
export interface IdentityArgs {
    readonly address?: pulumi.Input<inputs.IdentityAddress>;
    readonly identification?: pulumi.Input<inputs.IdentityIdentification>;
    readonly internet?: pulumi.Input<inputs.IdentityInternet>;
    readonly name?: pulumi.Input<string>;
    readonly notes?: pulumi.Input<string>;
    readonly sections?: pulumi.Input<pulumi.Input<inputs.IdentitySection>[]>;
    readonly tags?: pulumi.Input<pulumi.Input<string>[]>;
    readonly vault?: pulumi.Input<string>;
}
